# Generated by Django 2.1.4 on 2019-01-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190103_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
