# Generated by Django 2.1.4 on 2019-01-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_airline_airport_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ind', models.IntegerField(primary_key=True, serialize=False)),
                ('cons_code', models.TextField(blank=True, null=True)),
                ('pn', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sn', models.TextField(blank=True, null=True)),
                ('app_code', models.TextField(blank=True, null=True)),
                ('ctrl_number', models.IntegerField(blank=True, null=True)),
                ('mfg_code', models.TextField(blank=True, null=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('part_cert_number', models.TextField(blank=True, null=True)),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('rec_date', models.DateTimeField(blank=True, null=True)),
                ('rep_date', models.DateTimeField(blank=True, null=True)),
                ('rcvr', models.TextField(blank=True, null=True)),
                ('qty_avl', models.IntegerField(blank=True, null=True)),
                ('qty_oh', models.IntegerField(blank=True, null=True)),
                ('total_qty', models.IntegerField(blank=True, null=True)),
                ('lcn_code', models.TextField(blank=True, null=True)),
                ('warehouse_code', models.TextField(blank=True, null=True)),
                ('cond', models.TextField(blank=True, null=True)),
                ('serialized', models.TextField(blank=True, null=True)),
                ('traceable_to', models.TextField(blank=True, null=True)),
                ('freight_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('obtained_from', models.TextField(blank=True, null=True)),
                ('trace_to', models.TextField(blank=True, null=True)),
                ('time_life', models.TextField(blank=True, null=True)),
                ('tag_date', models.DateTimeField(blank=True, null=True)),
                ('tagged_by', models.TextField(blank=True, null=True)),
                ('tag_details', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ils_flag_code', models.TextField(blank=True, null=True)),
                ('so_type', models.TextField(blank=True, null=True)),
                ('lp', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('lp_date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('mfg_usd_lp', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('exch_rate', models.IntegerField(blank=True, null=True)),
                ('visible_mkt', models.TextField(blank=True, null=True)),
                ('po_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('inv_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('cycle_rem', models.IntegerField(blank=True, null=True)),
                ('cycles_new', models.IntegerField(blank=True, null=True)),
                ('cycles_ovhl', models.TextField(blank=True, null=True)),
                ('time_rem', models.IntegerField(blank=True, null=True)),
                ('time_new', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('time_ovhl', models.TextField(blank=True, null=True)),
                ('po_number', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('repair_date', models.DateTimeField(blank=True, null=True)),
                ('ata', models.TextField(blank=True, db_column='ATA', null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SqliteStat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl', models.TextField(blank=True, null=True)),
                ('idx', models.TextField(blank=True, null=True)),
                ('stat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sqlite_stat1',
                'managed': False,
            },
        ),
    ]
