# Generated by Django 2.1.4 on 2019-01-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_inventory_sqlitestat1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('consignment_code', models.TextField(blank=True, db_column='Consignment Code', null=True)),
                ('project', models.TextField(blank=True, db_column='Project', null=True)),
                ('po', models.TextField(blank=True, db_column='PO', null=True)),
                ('application_code', models.TextField(blank=True, db_column='Application Code', null=True)),
                ('tag_field', models.TextField(db_column='Tag #', primary_key=True, serialize=False)),
                ('rec_date', models.TextField(blank=True, db_column='REC Date', null=True)),
                ('stk_field', models.IntegerField(blank=True, db_column='STK #', null=True)),
                ('route_code', models.TextField(blank=True, db_column='Route Code', null=True)),
                ('pn', models.TextField(blank=True, db_column='PN', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('cond', models.TextField(blank=True, db_column='COND', null=True)),
                ('sn', models.TextField(blank=True, db_column='SN', null=True)),
                ('loc_whse', models.TextField(blank=True, db_column='LOC / WHSE', null=True)),
                ('ro_field', models.TextField(blank=True, db_column='RO #', null=True)),
                ('so_field', models.TextField(blank=True, db_column='SO #', null=True)),
                ('invc_field', models.TextField(blank=True, db_column='INVC #', null=True)),
                ('invc_date', models.TextField(blank=True, db_column='INVC Date', null=True)),
                ('ship_date', models.TextField(blank=True, db_column='Ship Date', null=True)),
                ('post_date', models.TextField(blank=True, db_column='Post Date', null=True)),
                ('inv_status', models.TextField(blank=True, db_column='INV Status', null=True)),
                ('inv_qty', models.IntegerField(blank=True, db_column='INV Qty', null=True)),
                ('gross_sales', models.DecimalField(blank=True, db_column='Gross Sales', decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.TextField(blank=True, db_column='Total Cost', null=True)),
                ('freight_cost', models.TextField(blank=True, db_column='Freight Cost', null=True)),
                ('tax_amt', models.TextField(blank=True, db_column='Tax AMT', null=True)),
                ('commision_commission', models.TextField(blank=True, db_column='Commision\nCommission', null=True)),
                ('unit_price_unit_price', models.TextField(blank=True, db_column='Unit Price\nUnit Price', null=True)),
                ('ovhl_cost', models.TextField(blank=True, db_column='OVHL Cost', null=True)),
                ('unit_cost', models.TextField(blank=True, db_column='Unit Cost', null=True)),
                ('net_sales', models.TextField(blank=True, db_column='Net Sales', null=True)),
                ('list_price', models.TextField(blank=True, db_column='List Price', null=True)),
                ('lp_date', models.TextField(blank=True, db_column='LP Date', null=True)),
                ('company_name_code_field', models.TextField(blank=True, db_column='Company Name (Code)', null=True)),
                ('contact', models.TextField(blank=True, db_column='Contact', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('user_name', models.TextField(blank=True, db_column='User Name', null=True)),
                ('customer_type', models.TextField(blank=True, db_column='Customer Type', null=True)),
                ('airline', models.TextField(blank=True, db_column='Airline', null=True)),
                ('repair', models.TextField(blank=True, db_column='Repair', null=True)),
                ('remarks', models.TextField(blank=True, db_column='REMARKS', null=True)),
                ('time_life', models.TextField(blank=True, db_column='TIME_LIFE', null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
